### ISSUE TITLE
Wallmart crashing very often

### ISSUE THREAD

**Issue by dasilva333** [shinvou/Wallmart#1]
There is a problem when using this app it constantly crashes my phone provided here is one of the crashes including the crash log and syslog.

crash log: https://gist.github.com/dasilva333/8c092656627158bfb1b9
sys log: https://gist.github.com/dasilva333/9ee4f782f6d34a93d76e

Any help would be great thanks

**Comment by shinvou** [comment]
That looks like a bug to me. Nonetheless I can't help you out since I'm not working on Wallmart anymore.

**Comment by dasilva333** [comment]
Is there anyone working on Wallmart? This project was opened 2 months ago and it would be great if you could at least explain how you got it to work on your device.

What iOS version did you test this with?
Did you have any issues on the IOS version you used?
Is there a possibility that a third party application is conflicting with Wallmart?

If you could at least answer these questions it would help me find a solution.

Thanks

**Comment by shinvou** [comment]
I tested it on iOS 8.1.2 on the same device you have, a iPhone 5s.
No, I didn't have any issues at all.
Yes, that's probably the case.

**Comment by dasilva333** [comment]
Perhaps the issue is I'm not using 8.1.2 I'm also using an iPhone 5s I'll try uninstalling all my other tweaks and updating and will report back on my results.

Thanks again
